### Test root ruta
GET http://localhost:3000/

### Test generate-model ruta
POST https://llm-data-modeling-backend.onrender.com/api/generate-model
Content-Type: application/json

{
  "description": "Web trgovina prodaje proizvode. Kupci mogu napraviti više narudžbi.",
  "provider": "claude"
}